import type { Metadata } from 'next';
import { Yuji_Mai, Dela_Gothic_One, Potta_One } from 'next/font/google';
import './globals.css';

const yujiMai = Yuji_Mai({
  subsets: ['latin'], // 必要に応じてサブセットを指定
  weight: ['400'], // 使用するウェイトを指定
});

const delaGothicOne = Dela_Gothic_One({
  subsets: ['latin'], // 必要に応じてサブセットを指定
  weight: ['400'], // 使用するウェイトを指定
});

const pottaOne = Potta_One({
  subsets: ['latin'], // 必要に応じてサブセットを指定
  weight: ['400'], // 使用するウェイトを指定
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${delaGothicOne.className} antialiased bg-cover bg-center bg-fixed bg-[url('/kami.jpeg')]`}
      >
        {children}
      </body>
    </html>
  );
}
