import type { Metadata } from 'next';
import { Potta_One } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from "@/components/theme-provider"


const pottaOne = Potta_One({
  subsets: ['latin'], // 必要に応じてサブセットを指定
  weight: ['400'], // 使用するウェイトを指定
});

export const metadata: Metadata = {
  title: '画像生成バトル',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
      // 文字フォントの指定
        className={`${pottaOne.className} antialiased bg-cover bg-center bg-fixed bg-[url('/kami.jpeg')]`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
