import type { Metadata } from 'next';
import { Potta_One } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/styles/theme-provider';
import { BgmProvider } from '@/context/BgmContext';
import { Toaster } from '@/components/ui/sonner';

const pottaOne = Potta_One({
  subsets: ['latin'], // 必要に応じてサブセットを指定
  weight: ['400'], // 使用するウェイトを指定
});

export const metadata: Metadata = {
  title: '画像生成バトル',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        // 文字フォントの指定
        className={`${pottaOne.className} antialiased bg-cover bg-center bg-fixed bg-[url('/kami.jpeg')]`}
      >
        <BgmProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
          <Toaster />
        </BgmProvider>
      </body>
    </html>
  );
}
